=== yuhongcqupt/ATCLM/v91/sys/namespace/info/v1/info.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="callback">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="dependency">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="dialogpref_registrar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="source" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="help_addon">
    <xs:complexType mixed="true">
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="category" type="xs:NMTOKEN" use="optional" />
      <xs:attribute name="productlevel" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="product_name_ends_with_type" type="xs:NMTOKEN" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="help_location">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="help_contents_icon">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="icon">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="label">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="listitem" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="listitem">
    <xs:complexType>
      <xs:all>
    <xs:element ref="dependency" minOccurs="0"/>
        <xs:element ref="label" />
        <xs:element ref="callback" />
        <xs:element ref="unsupported-platform" minOccurs="0"/>
        <xs:element ref="icon" />
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="matlabrelease">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="name">
    <xs:complexType mixed="true" />
  </xs:element>

<xs:element name="MathWorksID" type="xs:integer"/>

  <xs:element name="preference_panel">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="label" />
        <xs:element ref="source" />
        <xs:element ref="preference_panel" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="product_name_ends_with_type">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="productinfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="matlabrelease" />
        <xs:element ref="name" />
        <xs:element ref="MathWorksID" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="type" />
        <xs:element ref="icon" />
        <xs:element ref="help_location" minOccurs="0"/>
        <xs:element ref="help_contents_icon" minOccurs="0"/>
        <xs:element ref="product_name_ends_with_type" minOccurs="0"/>
        <xs:element ref="help_addon" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="preference_panel" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="dialogpref_registrar" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="list" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="source">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="type">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="unsupported-platform">
    <xs:complexType mixed="true" />
  </xs:element>

</xs:schema>

=== yuhongcqupt/ATCLM/v91/mcr/toolbox/matlab/general/info.xml
<productinfo
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.mathworks.com/namespace/info/v1/info.xsd">
<?xml-stylesheet type="text/xsl" href="http://www.mathworks.com/namespace/info/v1/info.xsl"?>


<matlabrelease>14</matlabrelease>
<name>MATLAB</name>
<type>matlab</type>
<icon>ApplicationIcon.MATLAB</icon>
<help_location>$docroot/techdoc</help_location>

<dialogpref_registrar>  
    <source>com.mathworks.mde.editor.EditorOptions</source>
</dialogpref_registrar>
<dialogpref_registrar>  
    <source>com.mathworks.mde.cmdhist.CmdHistoryPrefs</source>
</dialogpref_registrar>
<dialogpref_registrar>  
    <source>com.mathworks.mlwidgets.workspace.WorkspaceDialogs</source>
</dialogpref_registrar>
<dialogpref_registrar>  
    <source>com.mathworks.toolbox.matlab.guide.LayoutPrefs</source>
</dialogpref_registrar> 
<dialogpref_registrar> 
    <source>com.mathworks.mlwidgets.explorer.extensions.matlab.MATFileUtils</source>
</dialogpref_registrar> 	

<list>

<listitem>
<label>Import Wizard</label>
<callback>uiimport</callback>
<icon>ApplicationIcon.GENERIC_GUI</icon>
</listitem>

<listitem>
<label>Profiler</label>
<callback>profile viewer</callback>
<icon>ApplicationIcon.PROFILER</icon>
</listitem>

<listitem>
<label>GUIDE (GUI Builder)</label>
<callback>guide</callback>
<icon>ApplicationIcon.GUIDE</icon>
</listitem>

<listitem>
<label>Notebook</label>
<callback>notebook</callback>
<unsupported-platform>unix</unsupported-platform>
<icon>ApplicationIcon.GENERIC_GUI</icon>
</listitem>

<listitem>
<label>Plot Tools</label>
<callback>figure; plottools</callback>
<icon>ApplicationIcon.GENERIC_GUI</icon>
</listitem>

<listitem>
<label>Time Series Tools</label>
<callback>tstool</callback>
<icon>ApplicationIcon.GENERIC_GUI</icon>
</listitem>

<listitem>
<label>Help</label>
<callback>doc matlab/</callback>
<icon>$toolbox/matlab/icons/book_mat.gif</icon>
</listitem>

<listitem>
<label>Demos</label>
<callback>demo matlab</callback>
<icon>ApplicationIcon.DEMOS</icon>
</listitem>

<listitem>
<label>MATLAB Central (Web)</label>
<callback>web http://www.mathworks.com/matlabcentral_redirect -browser;</callback>
<icon>CommonIcon.WEB</icon>
</listitem>

<listitem>
<label>Product Page (Web)</label>
<callback>web http://www.mathworks.com/products/matlab/ -browser;</callback>
<icon>CommonIcon.WEB</icon>
</listitem>

</list>

</productinfo>
